# Generated by Django 2.2.2 on 2019-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterurls', '0002_auto_20190624_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedurls',
            name='full_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='storedurls',
            name='short_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
